import { StyleSheet, Platform } from 'react-native';

const buildTokens = (theme) => ({
    surface:      theme.colors.surface      ?? '#FFFFFF',
    surfaceAlt:   theme.colors.surfaceAlt   ?? '#F7F7F8',
    border:       theme.colors.borde        ?? '#E8E8EC',
    text:         theme.colors.texto,
    textMuted:    theme.colors.grisTexto,
    accent:       theme.colors.naranja,
    radiusXS:  8,
    radiusSM:  12,
    radiusMD:  16,
    radiusLG:  20,
    radiusXL:  28,
    radiusPill: 100,
    spaceXS:  6,
    spaceSM:  12,
    spaceMD:  20,
    spaceLG:  25,
    spaceXL:  30,
    shadowLight: Platform.select({
        ios: {
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 2 },
            shadowOpacity: 0.06,
            shadowRadius: 8,
        },
        android: { elevation: 3 },
    }),
    shadowMedium: Platform.select({
        ios: {
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 4 },
            shadowOpacity: 0.10,
            shadowRadius: 12,
        },
        android: { elevation: 6 },
    }),
    shadowAccent: (accentColor) => Platform.select({
        ios: {
            shadowColor: accentColor,
            shadowOffset: { width: 0, height: 4 },
            shadowOpacity: 0.30,
            shadowRadius: 8,
        },
        android: { elevation: 4 },
    }),
});

export const getShopStyles = (theme) => {
    const t = buildTokens(theme);

    return StyleSheet.create({
        container: {
            flex: 1,
            backgroundColor: t.surface,
            paddingHorizontal: t.spaceMD,
            paddingTop: 50,
        },
        header: {
            flexDirection: 'row',
            justifyContent: 'space-between',
            alignItems: 'center',
            paddingHorizontal: t.spaceLG,
            paddingVertical: t.spaceSM + 3,
            marginBottom: t.spaceMD,
            marginHorizontal: -t.spaceMD,
            backgroundColor: t.surface,
            borderBottomLeftRadius: t.radiusMD,
            borderBottomRightRadius: t.radiusMD,
            ...t.shadowLight,
        },
        headerTitle: {
            fontSize: 28,
            fontWeight: '800',
            color: '#000000',
            letterSpacing: 0.3,
            textAlign: 'center',
        },
        cartButton: {
            position: 'relative',
            padding: t.spaceXS - 1,
        },
        cartBadge: {
            position: 'absolute',
            top: -4,
            right: -4,
            width: 22,
            height: 22,
            borderRadius: t.radiusPill,
            backgroundColor: t.accent,
            justifyContent: 'center',
            alignItems: 'center',
            borderWidth: 2,
            borderColor: t.surface,
        },
        cartBadgeText: {
            color: t.surface,
            fontWeight: '800',
            fontSize: 10,
        },
        categoriasScroll: {
            marginBottom: t.spaceMD,
            marginHorizontal: -t.spaceMD,
            paddingHorizontal: t.spaceMD,
        },
        categoriaBtn: {
            paddingHorizontal: t.spaceMD,
            paddingVertical: t.spaceXS + 4,
            borderRadius: t.radiusPill,
            marginRight: t.spaceSM,
            borderWidth: 1.5,
            borderColor: t.border,
            backgroundColor: t.surface,
        },
        categoriaBtnActive: {
            borderWidth: 1.5,
            borderColor: t.accent,
            backgroundColor: t.accent,
        },
        categoriaBtnText: {
            fontWeight: '600',
            fontSize: 14,
            color: t.textMuted,
        },
        categoriaBtnTextActive: {
            fontWeight: '700',
            color: t.surface,
        },

        productsGrid: {
            paddingBottom: t.spaceXL,
        },
        productCard: {
            flex: 1,
            aspectRatio: 1,
            marginHorizontal: '1.5%',
            marginBottom: t.spaceSM + 3,
            padding: t.spaceSM + 3,
            borderRadius: t.radiusLG + 2,
            backgroundColor: t.surface,
            alignItems: 'center',
            justifyContent: 'center',
            borderWidth: 1,
            borderColor: t.border,
            ...t.shadowLight,
        },
        productImage: {
            fontSize: 45,
            marginBottom: t.spaceSM,
        },
        productImageUrl: {
            width: 80,
            height: 80,
            borderRadius: t.radiusSM,
            marginBottom: t.spaceSM,
            resizeMode: 'contain',
        },

        productName: {
            fontSize: 15,
            fontWeight: '700',
            textAlign: 'center',
            marginBottom: t.spaceXS,
            color: '#343434',
            lineHeight: 20,
        },
        productPrice: {
            fontSize: 16,
            fontWeight: '800',
            marginBottom: t.spaceSM,
            color: t.accent,
        },

        noProductosText: {
            fontSize: 16,
            textAlign: 'center',
            padding: 40,
            color: t.textMuted,
            fontWeight: '500',
            lineHeight: 24,
        },

        modalOverlay: {
            flex: 1,
            justifyContent: 'flex-end',
            backgroundColor: 'rgba(0,0,0,0.45)',
        },
        closeButton: {
            position: 'absolute',
            top: t.spaceMD,
            right: t.spaceMD,
            zIndex: 10,
            backgroundColor: t.border,
            padding: t.spaceXS - 1,
            borderRadius: t.radiusPill,
        },

        modalContent: {
            backgroundColor: t.surface,
            borderTopLeftRadius: t.spaceXL,
            borderTopRightRadius: t.spaceXL,
            padding: t.spaceLG,
            maxHeight: '90%',
            alignItems: 'center',
            ...t.shadowMedium,
        },
        modalImage: {
            fontSize: 90,
            marginVertical: t.spaceMD,
        },
        modalImageUrl: {
            width: 180,
            height: 180,
            borderRadius: t.radiusLG,
            marginVertical: t.spaceMD,
            resizeMode: 'contain',
        },
        modalTitle: {
            fontSize: 26,
            fontWeight: '800',
            textAlign: 'center',
            marginBottom: t.spaceXS + 2,
            color: t.text,
            lineHeight: 32,
        },
        modalPrice: {
            fontSize: 28,
            fontWeight: '900',
            marginBottom: t.spaceSM + 3,
            color: t.accent,
        },
        modalDescription: {
            fontSize: 15,
            textAlign: 'center',
            marginBottom: t.spaceMD,
            lineHeight: 23,
            color: t.textMuted,
            paddingHorizontal: t.spaceSM - 2,
        },
        modalStock: {
            fontSize: 14,
            fontWeight: '600',
            marginBottom: t.spaceLG,
            color: t.textMuted,
            backgroundColor: t.surfaceAlt,
            paddingHorizontal: t.spaceSM,
            paddingVertical: t.spaceXS,
            borderRadius: t.radiusSM - 2,
            borderWidth: 1,
            borderColor: t.border,
            overflow: 'hidden',
        },
        buyButton: {
            width: '100%',
            paddingVertical: t.spaceSM + 4,   // 16 px
            borderRadius: t.radiusMD - 1,
            alignItems: 'center',
            backgroundColor: t.accent,
            ...t.shadowAccent(t.accent),
        },
        buyButtonText: {
            color: t.surface,
            fontWeight: '800',
            fontSize: 16,
            letterSpacing: 0.4,
        },

        cartModalContent: {
            flex: 0.85,
            backgroundColor: t.surface,
            borderTopLeftRadius: t.spaceXL,
            borderTopRightRadius: t.spaceXL,
            paddingBottom: t.spaceMD,
            ...t.shadowMedium,
        },
        cartHeader: {
            flexDirection: 'row',
            justifyContent: 'space-between',
            alignItems: 'center',
            padding: t.spaceLG,
            borderBottomWidth: 1,
            borderBottomColor: t.border,
        },
        cartTitle: {
            fontSize: 24,
            fontWeight: '800',
            color: t.text,
        },

        emptyCart: {
            flex: 1,
            justifyContent: 'center',
            alignItems: 'center',
            gap: t.spaceSM,
        },
        emptyCartText: {
            fontSize: 17,
            fontWeight: '500',
            color: t.textMuted,
        },

        cartItem: {
            flexDirection: 'row',
            alignItems: 'center',
            padding: t.spaceSM + 3,
            marginHorizontal: t.spaceMD,
            marginVertical: t.spaceXS + 2,
            borderRadius: t.radiusMD,
            backgroundColor: t.surface,
            borderWidth: 1,
            borderColor: t.border,
        },
        cartItemImage: {
            fontSize: 35,
            marginRight: t.spaceSM + 3,
        },
        cartItemImageUrl: {
            width: 50,
            height: 50,
            borderRadius: t.radiusSM - 2,
            marginRight: t.spaceSM + 3,
            resizeMode: 'contain',
        },
        cartItemInfo: {
            flex: 1,
        },
        cartItemName: {
            fontSize: 15,
            fontWeight: '700',
            marginBottom: 4,
            color: t.text,
            lineHeight: 20,
        },
        cartItemPrice: {
            fontSize: 15,
            fontWeight: '700',
            color: t.accent,
        },

        cartTotal: {
            flexDirection: 'row',
            justifyContent: 'space-between',
            alignItems: 'center',
            paddingHorizontal: t.spaceLG,
            paddingVertical: t.spaceMD,
            borderTopWidth: 1,
            borderTopColor: t.border,
            backgroundColor: t.surface,
        },
        cartTotalText: {
            fontSize: 18,
            fontWeight: '700',
            color: t.text,
        },
        cartTotalPrice: {
            fontSize: 26,
            fontWeight: '900',
            color: t.accent,
        },

        checkoutButton: {
            marginHorizontal: t.spaceMD,
            marginBottom: t.spaceSM - 2,
            paddingVertical: t.spaceSM + 4,
            borderRadius: t.radiusMD - 1,
            backgroundColor: t.accent,
            alignItems: 'center',
            ...t.shadowAccent(t.accent),
        },
        checkoutButtonText: {
            color: t.surface,
            fontWeight: '800',
            fontSize: 16,
            letterSpacing: 0.4,
        },
    });
};